### ISSUE TITLE
Support request: Adjust number or processes

### ISSUE THREAD

**Issue by physikerwelt** [dginev/LaTeXML-Plugin-ltxmojo#7]
Risking that this might not be the optimal place for this question...

Is there a parameter to adjust how many processes are started simultaneously. I have 64 cores available to my docker instance, but there are only 4+1 (/opt/ltxmojo/sc) processes started

**Comment by dginev** [comment]
Curiously enough the `devops` part of mojolicious web servers is external to the code itself. So it depends on how you start the process. If you reverse-proxy through nginx, you can either do your own load-balancing, start individual processes on different ports, etc (which was my approach with `latexmls`), or probably much better - use a `hypnotoad` process which will auto-manage the load balancing between workers for you (but the configuration for the workers has to be set in a config file I think).

Documentation is here:
https://mojolicious.org/perldoc/Mojolicious/Guides/Cookbook#Pre-forking

One (of I think several) ways of getting to what you need is:
```
./script/my_app prefork -w 64 -c 1 -m production -l http://*:8080
```
or something along those lines.

Usual warning that I haven't used this particular plugin in production before myself, just for the showcase demos.

**Comment by dginev** [comment]
I personally would feel most comfortable doing deployment here with hypnotoad (because it has been stress-tested in production settings for multiple years, so it should be quite robust).

https://mojolicious.org/perldoc/Mojolicious/Guides/Cookbook#Hypnotoad

**Comment by physikerwelt** [comment]
Thanks a lot.
Fortunately, I am already using `hypnotoad` in my [Dockerfile](https://github.com/ag-gipp/node-moi-helper/blob/master/Dockerfile) which I adopted from @tkw1536 . Now, I understand that I have to overwrite the settingsfile and that's it.

**Comment by dginev** [comment]
Cool!
