### ISSUE TITLE
forms are using GET requests for sensitive stuff

### ISSUE THREAD

**Issue by woodfighter** [dginev/LaTeXML-Plugin-ltxmojo#8]
The forms under the /login and /admin route are GET based and thus lead to passwords in browser histories, web server and proxy log files. Furthermore GET requests are for retrieving not changing information, so shouldn't be used in the admin interface.

**Comment by dginev** [comment]
Thanks @woodfighter . These forms are leftovers from pre-release experiments that required authentication. As things stand the showcase doesn't ever use /login or /admin, so they are safe to delete entirely. Will take a quick pass today and eliminate as much cruft as I can see.

**Comment by woodfighter** [comment]
ah thx; sorry just stumbled upon it and I'll wait with further issues that are probably related to said cruft.
