### ISSUE TITLE
the secret used to encrypt cookies should not be the same for every running instance

### ISSUE THREAD

**Issue by woodfighter** [dginev/LaTeXML-Plugin-ltxmojo#9]
The secret which is used by mojolicious to encrypt cookies is set in an unconfigurable way to the string 'LaTeXML is the way to go!'.

**Comment by dginev** [comment]
Hey @woodfighter what would be the best practice to change to here? Also, is it of relevance if the web service never actually relies on cookies directly?

**Comment by woodfighter** [comment]
If it's not used, best practice would probably be to set it to a random value at startup as mojolicious unfortunately otherwise sets it to another unsafe value (but it at least logs about it).

**Comment by dginev** [comment]
Thanks, did something to that extent - 10bde30c4cd82db27213a058aa45e740b16709d3
